// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Biography *string `json:"biography,omitempty"`
	Birthday  *string `json:"birthday,omitempty"`
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	Username  string  `json:"username"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse User

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`

	// エラー内容
	Type *string `json:"type,omitempty"`
}

// User defines model for User.
type User struct {
	Biography     *string `json:"biography,omitempty"`
	Birthday      *string `json:"birthday,omitempty"`
	Email         string  `json:"email"`
	FirebaseId    *string `json:"firebase_id,omitempty"`
	Id            *string `json:"id,omitempty"`
	Name          string  `json:"name"`
	ProfileImgUrl *string `json:"profile_img_url,omitempty"`
	Username      string  `json:"username"`
}

// BadRequest defines model for BadRequest.
type BadRequest Error

// InternalServerError defines model for InternalServerError.
type InternalServerError Error

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody CreateUserRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

