version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toriton
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  app:
    build: .
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./..:/go/src/work
    command: go run app/cmd/main.go